spring.application.name=metacheck

# 서버 포트 (EC2에서 열어둔 8080 포트)
server.port=8080

# RDS MariaDB 연결
spring.datasource.url=jdbc:mariadb://my-mariadb.c3mqe6qusywd.ap-southeast-2.rds.amazonaws.com:3306/myapp?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=admin
spring.datasource.password=Pp612625!
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true